<?php
namespace app\components;

use common\models\Order;
use yii\base\Widget;

class NewOrdersCount extends Widget
{
    public $tooltip = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    public function run()
    {
        $query = Order::find();
        if (!$this -> tooltip) {
            $count = $query->where('viewed = false and status="confirmed"')->count();
            return $count;
        }
        else {
            $orders = $query -> where('viewed = false and status="confirmed"') -> all();
            $html = '';
            foreach($orders as $order){
                $html .= '<a href="/admin/orders/'.$order['id'].'">Заказ №'.date('y').'0'.$order['id'].'</a><br>';
            }
            return $html;
        }
    }
}